floorplan:
	./run_backend.sh --floorplan

placement:
	./run_backend.sh --placement

cts:
	./run_backend.sh --cts

routing:
	./run_backend.sh --routing

finishing:
	./run_backend.sh --finishing

all:
	./run_backend.sh --all

clean:
	rm -rf ./out/
	rm -rf ./tmp/
	rm -rf ./reports/
